name: playground_app
description: Playground application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Core
  analyzer: 6.2.0
  flutter:
    sdk: flutter

  # Bloc
  flutter_bloc: 8.1.4

  # MobX
  flutter_mobx: 2.2.0+2
  mobx: 2.3.0+1

  # Riverpod
  flutter_riverpod: 2.4.10
  riverpod_annotation: 2.3.4

dev_dependencies:
  #Core
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # MobX
  mobx_codegen: 2.6.0+1

  # Riverpod
  riverpod_generator: 2.3.11
  riverpod_lint: 2.3.9

  # Tests
  mocktail: 1.0.1

flutter:
  uses-material-design: true
